package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

public record AnswerDto(

        @Schema(
                description = "Unique identifier of the question. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "The text content of the answer that is shown to the user.",
                example = "The capital of France is Paris."
        )
        String text,

        @Schema(
                description = "Whether the answer is correct or not.",
                example = "true"
        )
        Boolean isCorrect,

        @Schema(
                description = "Question this answer refers to.",
                implementation = QuestionSlimDto.class
        )
        QuestionSlimDto question

) {
}
