package at.learnhub.dto.simple;

import at.learnhub.model.MediaFile;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDateTime;
import java.util.List;

@Schema(description = "Data transfer object representing an exam instance, including selected topic pools and assigned questions.")
public record ExamDto(

        @Schema(
                description = "Unique identifier of the exam, generated by the system.",
                example = "101",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "Time limit for the exam in minutes.",
                example = "60"
        )
        Integer timeLimit,

        @Schema(
                description = "Timestamp when the exam was started.",
                example = "2025-07-10T14:30:00"
        )
        LocalDateTime startedAt,

        @Schema(
                description = "Timestamp when the exam was finished.",
                example = "2025-07-10T15:15:00"
        )
        LocalDateTime finishedAt,

        @Schema(
                description = "Total number of questions included in this exam.",
                example = "20"
        )
        Integer questionCount,

        @Schema(
                description = "Final score achieved in this exam (0.0 - 100.0).",
                example = "87.5"
        )
        Double score,

        @Schema(
                description = "The user who took this exam.",
                implementation = UserSlimDto.class
        )
        UserSlimDto user,

        @Schema(
                description = "The topic pools selected for this exam.",
                implementation = TopicPoolSlimDto.class,
                type = SchemaType.ARRAY
        )
        List<TopicPoolSlimDto> topicPools,

        @Schema(
                description = "The list of exam-specific questions that were presented to the user.",
                implementation = ExamQuestionSlimDto.class,
                type = SchemaType.ARRAY
        )
        List<ExamQuestionSlimDto> questions

) {}