package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema(description = "DTO representing a media file.")
public record MediaFileDto(

        @Schema(description = "Unique identifier of the media file. Generated by the system.", example = "10", readOnly = true)
        Long id,

        @Schema(description = "Filesystem or URL path where the media file is stored.", example = "/uploads/images/photo123.jpg")
        String path,

        @Schema(description = "Type of the media file, e.g., 'img' for images, 'pdf' for PDF documents.", example = "img")
        String type,

        @Schema(description = "Optional description or title of the media file.", example = "Profile picture of the user")
        String description,

        @Schema(description = "Timestamp when the media file was uploaded.", example = "2025-07-10T09:30:00", readOnly = true)
        LocalDateTime uploadedAt
) {}
