package at.learnhub.dto.simple;

import at.learnhub.model.MediaFile;
import at.learnhub.model.QuestionType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

@Schema(description = "Slim version of the DTO representing a quiz question without relations.")
public record QuestionSlimDto(

        @Schema(
                description = "Unique identifier of the question. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "The main text or body of the question presented to the user.",
                example = "What is the capital of France?"
        )
        String text,

        @Schema(
                description = "Detailed explanation behind the correct answer(s). Useful for feedback.",
                example = "Paris is the capital and largest city of France."
        )
        String explanation,

        @Schema(
                description = "Optional media file associated with this question (e.g., image, diagram).",
                implementation = MediaFile.class
        )
        MediaFile media,

        @Schema(
                description = "Numerical code representing the question type (e.g., multiple choice, freetext).",
                example = "1",
                implementation = QuestionType.class
        )
        QuestionType type,

        @Schema(
                description = "Difficulty level of the question, e.g., 1 (easy) to 3 (hard).",
                example = "3"
        )
        Integer difficulty,

        @Schema(
                description = "Whether this question is publicly available to all users.",
                example = "true"
        )
        Boolean isPublic

) {}
