package at.learnhub.dto.simple;

import at.learnhub.model.MediaFile;
import at.learnhub.model.QuestionPoolEntry;
import at.learnhub.model.QuestionType;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

@Schema(description = "DTO representing a question pool associated to a user")
public record QuestionPoolDto(

        @Schema(
                description = "Unique identifier of the question pool. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "User who owns this question pool",
                implementation = UserSlimDto.class
        )
        UserSlimDto user,

        @Schema(
                description = "Entries of this question pool, containing the individual questions and answer history",
                implementation = QuestionPoolEntry.class,
                type = SchemaType.ARRAY
        )
        List<QuestionPoolEntrySlimDto> entries

) {}
