package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema(description = "DTO representing a question pool entry held by a question pool")
public record QuestionPoolEntrySlimDto(

        @Schema(
                description = "Unique identifier of the question pool entry. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "Timestamp of the last time the question was answered by the user.",
                example = "2025-07-10T15:30:00"
        )
        LocalDateTime answeredAt,

        @Schema(
                description = "Indicates if the question was last answered correctly by the user.",
                example = "true"
        )
        Boolean lastAnsweredCorrectly,

        @Schema(
                description = "Number of consecutive times the question has been answered correctly by the user.",
                example = "2"
        )
        Integer correctCount,

        @Schema(
                description = "The question associated with this entry."
        )
        QuestionSlimDto question

) {}