package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

public record SolutionSlimDto(

        @Schema(
                description = "Unique identifier of the question. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "List of detailed steps that make up this solution.",
                implementation = SolutionStepDto.class,
                type = SchemaType.ARRAY
        )
        List<SolutionStepDto> steps,

        @Schema(
                description = "Amount of up-votes received. +1 per up-vote, -1 per down-vote."
        )
        Long upVotes

) {
}
