package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

public record SolutionStepDto(

        @Schema(
                description = "Unique identifier of the question. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "Title or short summary of this step.",
                example = "Step 1: Identify variables"
        )
        String title,

        @Schema(
                description = "Detailed explanation or content of this step.",
                example = "Define the variables x and y based on the problem statement."
        )
        String text

) {
}
