package at.learnhub.dto.simple;

import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

public record SolutionVoteSlimDto(

        @Schema(
                description = "Unique identifier of the question. Generated by the system.",
                example = "123",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "Whether the vote was an up- or down-vote.",
                type = SchemaType.ARRAY
        )
        Boolean isUpvote

) {
}
