package at.learnhub.dto.simple;

import at.learnhub.model.MediaFile;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

@Schema(description = "Data transfer object representing a subject or field of study, containing related topic pools.")
public record SubjectDto(

        @Schema(
                description = "Unique identifier for the subject, generated by the system.",
                example = "3",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "The name of the subject.",
                example = "Mathematics"
        )
        String name,

        @Schema(
                description = "A description of the subject.",
                example = "Covers topics like algebra, calculus, and geometry."
        )
        String description,

        @Schema(
                description = "Optional image representing the subject.",
                implementation = MediaFile.class
        )
        MediaFile img,

        @Schema(
                description = "List of topic pools related to this subject.",
                implementation = TopicPoolSlimDto.class,
                type = SchemaType.ARRAY
        )
        List<TopicPoolSlimDto> topicPools

) {}
