package at.learnhub.dto.simple;

import at.learnhub.model.MediaFile;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(description = "Slim version of the Subject DTO, containing only basic subject details and no relations.")
public record SubjectSlimDto(

        @Schema(
                description = "Unique identifier for the subject, generated by the system.",
                example = "3",
                readOnly = true
        )
        Long id,

        @Schema(
                description = "The name of the subject.",
                example = "Mathematics"
        )
        String name,

        @Schema(
                description = "A description of the subject.",
                example = "Covers topics like algebra, calculus, and geometry."
        )
        String description,

        @Schema(
                description = "Optional image representing the subject.",
                implementation = MediaFile.class
        )
        MediaFile img

) {}
