services:

  frontend:
    image: nginx
    container_name: learnhub-ui
    restart: always
    networks:
      - learnhubnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`vm91.htl-leonding.ac.at`) && PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"  

  # backend:
  #   image: todo
  #   container_name: webapi_backend
  #   restart: always
  #   environment:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.webapi.rule=Host(`vm91.htl-leonding.ac.at`) && PathPrefix(`/api`)"
  #     - "traefik.http.services.webapi.loadbalancer.server.port=8080"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - learnhubnet

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - learnhubnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`vm91.htl-leonding.ac.at`) && PathPrefix(`/adminer`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"  
      - "traefik.http.middlewares.adminer-strip-prefix.stripprefix.prefixes=/adminer"
      - "traefik.http.routers.adminer.middlewares=adminer-strip-prefix"

  mysql:
    image: mysql:8.4.3
    container_name: mysql_db
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: learnhub
      MYSQL_PASSWORD: learnhub
      MYSQL_DATABASE: learnhub
    volumes:
      - learnhub-data:/var/lib/mysql
    networks:
      - learnhubnet

networks:
  learnhubnet:
    external: true

volumes:
  learnhub-data:
    name: learnhub-data
