package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

/**
 * Represents an answer option for a specific quiz question.
 */
@Entity
public class Answer {

    /**
     * Unique identifier for the answer, generated by the system.
     * This field should not be provided in client requests.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The text content of the answer that is shown to the user.
     */
    private String text;

    /**
     * Flag indicating whether this answer is correct.
     */
    @Column(name = "is_correct")
    private Boolean isCorrect;

    /**
     * The question to which this answer belongs.
     */
    @ManyToOne
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties({"answers"})
    private Question question;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getCorrect() {
        return isCorrect;
    }

    public void setCorrect(Boolean correct) {
        isCorrect = correct;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }
}
