package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Entity
@Schema(description = "Represents an answer option for a specific quiz question.")
public class Answer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier (generated by the system). Do not provide this in requests.",
            example = "42",
            readOnly = true
    )
    private Long id;

    @Schema(
            description = "The text of the answer shown to the user.",
            example = "Paris"
    )
    private String text;

    @Column(name = "is_correct")
    @Schema(
            description = "Indicates whether this answer is correct.",
            example = "true"
    )
    private Boolean isCorrect;

    @ManyToOne
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties({"answers"})
    private Question question;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getCorrect() {
        return isCorrect;
    }

    public void setCorrect(Boolean correct) {
        isCorrect = correct;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }
}
