package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a single question within an exam session, including selected answers and evaluation result.
 */
@Entity
@Table(name = "exam_question", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"exam_id", "entry_id"})
})
public class ExamQuestion {

    /**
     * Unique identifier of the exam question. Generated by the system.
     * Example: 3001
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The exam session this question belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "exam_id", nullable = false)
    @JsonIgnoreProperties({"questions", "user"})
    private Exam exam;

    /**
     * The original question pool entry this exam question was derived from.
     */
    @ManyToOne
    @JoinColumn(name = "entry_id", nullable = false)
    @JsonIgnoreProperties("examQuestions")
    private QuestionPoolEntry entry;

    /**
     * The list of answers selected by the user for this question.
     */
    @ManyToMany
    @JoinTable(
            name = "exam_question_selected_answers",
            joinColumns = @JoinColumn(name = "exam_question_id"),
            inverseJoinColumns = @JoinColumn(name = "answer_id")
    )
    @JsonIgnoreProperties({"examQuestions", "question"})
    private List<Answer> selectedAnswers;

    /**
     * User-provided free text answer (for open-ended questions).
     * Example: "The capital of France is Paris."
     */
    @Column(name = "freet_text_answer")
    private String freeTextAnswer;

    /**
     * Whether the user's answer(s) were evaluated as correct.
     * Example: false
     */
    @Column(name = "is_correct")
    private Boolean isCorrect;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Exam getExam() {
        return exam;
    }

    public void setExam(Exam exam) {
        this.exam = exam;
    }

    public QuestionPoolEntry getEntry() {
        return entry;
    }

    public void setEntry(QuestionPoolEntry entry) {
        this.entry = entry;
    }

    public List<Answer> getSelectedAnswers() {
        return selectedAnswers;
    }

    public void setSelectedAnswers(List<Answer> selectedAnswers) {
        this.selectedAnswers = selectedAnswers;
    }

    public String getFreeTextAnswer() {
        return freeTextAnswer;
    }

    public void setFreeTextAnswer(String freeTextAnswer) {
        this.freeTextAnswer = freeTextAnswer;
    }

    public Boolean getCorrect() {
        return isCorrect;
    }

    public void setCorrect(Boolean correct) {
        isCorrect = correct;
    }
}
