package at.learnhub.model;

import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDateTime;

@Entity
@Table(name = "media_file")
@Schema(description = "Represents a media file stored in the system, such as images or PDFs.")
public class MediaFile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier of the media file. Generated by the system.",
            example = "10",
            readOnly = true
    )
    private Long id;

    @Schema(
            description = "Filesystem or URL path where the media file is stored.",
            example = "/uploads/images/photo123.jpg"
    )
    private String path;

    @Schema(
            description = "Type of the media file, e.g., 'img' for images, 'pdf' for PDF documents.",
            example = "img"
    )
    private String type;

    @Schema(
            description = "Optional description or title of the media file.",
            example = "Profile picture of the user"
    )
    private String description;

    @Column(name = "uploaded_at")
    @Schema(
            description = "Timestamp when the media file was uploaded.",
            example = "2025-07-10T09:30:00",
            readOnly = true
    )
    private LocalDateTime uploadedAt;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getUploadedAt() {
        return uploadedAt;
    }

    public void setUploadedAt(LocalDateTime uploadedAt) {
        this.uploadedAt = uploadedAt;
    }
}
