package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a personal collection of questions owned by a specific user.
 * Each user can have one question pool, which may contain multiple question entries.
 */
@Entity
@Table(name = "question_pool")
public class QuestionPool {

    /**
     * Unique identifier of the question pool.
     * This value is automatically generated by the system.
     * Example: 5
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this question pool.
     */
    @OneToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"user"})
    private User user;

    /**
     * The list of question pool entries contained in this pool.
     * Each entry represents a question that belongs to this pool.
     */
    @OneToMany(mappedBy = "questionPool")
    @JsonIgnoreProperties({"questionPool"})
    private List<QuestionPoolEntry> entries;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<QuestionPoolEntry> getEntries() {
        return entries;
    }

    public void setEntries(List<QuestionPoolEntry> entries) {
        this.entries = entries;
    }
}
