package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

@Entity
@Table(name = "question_pool")
@Schema(description = "Represents a personal collection of questions owned by a user.")
public class QuestionPool {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier of the question pool. Generated by the system.",
            example = "5",
            readOnly = true
    )
    private Long id;

    @OneToOne()
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"user"})
    private User user;

    @OneToMany(mappedBy = "questionPool")
    @JsonIgnoreProperties({"questionPool"})
    private List<QuestionPoolEntry> entries;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<QuestionPoolEntry> getEntries() {
        return entries;
    }

    public void setEntries(List<QuestionPoolEntry> entries) {
        this.entries = entries;
    }
}
