package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents an individual question entry within a user's personal question pool.
 * Tracks user progress such as correctness and answer history.
 */
@Entity
@Table(name = "question_pool_entry")
public class QuestionPoolEntry {

    /**
     * Unique identifier of the question pool entry.
     * This value is automatically generated by the system.
     * Example: 123
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Timestamp of the last time the question was answered by the user.
     * Example: 2025-07-10T15:30:00
     */
    @Column(name = "answered_at")
    private LocalDateTime answeredAt;

    /**
     * Indicates if the question was last answered correctly by the user.
     * Example: true
     */
    @Column(name = "last_answered_correctly")
    private Boolean lastAnsweredCorrectly;

    /**
     * Number of consecutive times the question has been answered correctly by the user.
     * Example: 2
     */
    @Column(name = "correct_count")
    private Integer correctCount;

    /**
     * The question associated with this entry.
     */
    @ManyToOne
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties({"entries", "user"})
    private Question question;

    /**
     * The question pool to which this entry belongs.
     */
    @ManyToOne
    @JoinColumn(name = "pool_id")
    @JsonIgnoreProperties({"entries", "user"})
    private QuestionPool questionPool;

    /**
     * A list of exam questions that reference this pool entry.
     */
    @OneToMany(mappedBy = "entry")
    @JsonIgnoreProperties({"entry"})
    private List<ExamQuestion> examQuestions;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getAnsweredAt() {
        return answeredAt;
    }

    public void setAnsweredAt(LocalDateTime answeredAt) {
        this.answeredAt = answeredAt;
    }

    public Boolean getLastAnsweredCorrectly() {
        return lastAnsweredCorrectly;
    }

    public void setLastAnsweredCorrectly(Boolean lastAnsweredCorrectly) {
        this.lastAnsweredCorrectly = lastAnsweredCorrectly;
    }

    public Integer getCorrectCount() {
        return correctCount;
    }

    public void setCorrectCount(Integer correctCount) {
        this.correctCount = correctCount;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    public QuestionPool getQuestionPool() {
        return questionPool;
    }

    public void setQuestionPool(QuestionPool questionPool) {
        this.questionPool = questionPool;
    }

    public List<ExamQuestion> getExamQuestions() {
        return examQuestions;
    }

    public void setExamQuestions(List<ExamQuestion> examQuestions) {
        this.examQuestions = examQuestions;
    }
}
