package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a quiz question including its content, metadata such as difficulty and type,
 * and relationships to answers, solutions, topic pools, and more.
 */
@Entity
public class Question {

    /**
     * Unique identifier of the question.
     * This is auto-generated by the system.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The main text or body of the question shown to the user.
     * Example: "What is the capital of France?"
     */
    private String text;

    /**
     * Explanation for the correct answer(s).
     * This is useful for giving feedback after the question is answered.
     */
    private String explanation;

    /**
     * Numerical code indicating the type of the question.
     * For example: 1 = multiple choice, 2 = free text, etc.
     */
    private Integer type;

    /**
     * Difficulty level of the question.
     * Usually represented as: 1 = easy, 2 = medium, 3 = hard.
     */
    private Integer difficulty;

    /**
     * Indicates whether the question is publicly visible to all users.
     */
    @Column(name = "is_public")
    private Boolean isPublic;

    /**
     * The topic pool this question belongs to.
     * Used for categorizing questions.
     */
    @ManyToOne
    @JoinColumn(name = "topic_pool_id")
    @JsonIgnoreProperties({"questions", "topicContents", "exams"})
    private TopicPool topicPool;

    /**
     * Optional media file (such as an image or diagram) associated with this question.
     */
    @ManyToOne
    @JoinColumn(name = "media_id")
    private MediaFile media;

    /**
     * The user who created this question.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"createdQuestions", "topicContents"})
    private User user;

    /**
     * List of possible answers for this question.
     */
    @OneToMany(mappedBy = "question")
    @JsonIgnoreProperties({"question"})
    private List<Answer> answers;

    /**
     * List of pool entries (i.e., assignments of this question to various question pools).
     */
    @OneToMany(mappedBy = "question")
    @JsonIgnoreProperties({"question"})
    private List<QuestionPoolEntry> entries;

    /**
     * List of submitted solutions for this question.
     */
    @OneToMany(mappedBy = "question")
    @JsonIgnoreProperties({"question"})
    private List<Solution> solutions;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    public Boolean getPublic() {
        return isPublic;
    }

    public void setPublic(Boolean aPublic) {
        isPublic = aPublic;
    }

    public TopicPool getTopicPool() {
        return topicPool;
    }

    public void setTopicPool(TopicPool topicPool) {
        this.topicPool = topicPool;
    }

    public MediaFile getMedia() {
        return media;
    }

    public void setMedia(MediaFile media) {
        this.media = media;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Answer> getAnswers() {
        return answers;
    }

    public void setAnswers(List<Answer> answers) {
        this.answers = answers;
    }

    public List<QuestionPoolEntry> getEntries() {
        return entries;
    }

    public void setEntries(List<QuestionPoolEntry> entries) {
        this.entries = entries;
    }

    public List<Solution> getSolutions() {
        return solutions;
    }

    public void setSolutions(List<Solution> solutions) {
        this.solutions = solutions;
    }
}
