package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a solution submitted by a user for a specific question.
 */
@Entity
public class Solution {

    /**
     * Unique identifier of the solution.
     * This value is generated by the system.
     * Example: 1001
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The question this solution belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties({"solutions", "user"})
    private Question question;

    /**
     * The user who submitted this solution.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({
            "solutions", "createdQuestions", "questionPool", "exams",
            "solutionVotes", "ownedTopicContents", "approvedTopicContents", "teacherOfTopicContents"
    })
    private User user;

    /**
     * List of detailed steps that make up this solution.
     */
    @OneToMany(mappedBy = "solution")
    @JsonIgnoreProperties({"solution"})
    private List<SolutionStep> steps;

    /**
     * List of votes (e.g., upvotes/downvotes) associated with this solution.
     */
    @OneToMany(mappedBy = "solution")
    @JsonIgnoreProperties({"solution"})
    private List<SolutionVote> votes;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<SolutionStep> getSteps() {
        return steps;
    }

    public void setSteps(List<SolutionStep> steps) {
        this.steps = steps;
    }

    public List<SolutionVote> getVotes() {
        return votes;
    }

    public void setVotes(List<SolutionVote> votes) {
        this.votes = votes;
    }
}
