package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Entity
@Table(name = "solution_vote")
@Schema(description = "Represents a user's vote (upvote or downvote) on a solution.")
public class SolutionVote {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier of the vote, generated by the system.",
            example = "1001",
            readOnly = true
    )
    private Long id;

    @Column(name = "is_up_vote")
    @Schema(
            description = "Indicates if the vote is an upvote (true) or a downvote (false).",
            example = "true"
    )
    private Boolean isUpVote;

    @ManyToOne
    @JoinColumn(name = "solution_id")
    @JsonIgnoreProperties({"votes", "user"})
    private Solution solution;

    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"solutionVotes", "solutions", "questionPool", "createdQuestions",
            "exams", "ownedTopicContents", "approvedTopicContents", "teacherOfTopicContents"})
    private User user;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getUpVote() {
        return isUpVote;
    }

    public void setUpVote(Boolean upVote) {
        isUpVote = upVote;
    }

    public Solution getSolution() {
        return solution;
    }

    public void setSolution(Solution solution) {
        this.solution = solution;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
