package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;


/**
 * Represents a single step in a solution to a question.
 */
@Entity
@Table(name = "solution_step")
public class SolutionStep {

    /**
     * Unique identifier of the solution step.
     * Generated by the system.
     * Example: 501
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title or short summary of this step.
     * Example: "Step 1: Identify variables"
     */
    private String title;

    /**
     * Detailed explanation or content of this step.
     * Example: "Define the variables x and y based on the problem statement."
     */
    private String text;

    /**
     * The solution this step belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "solution_id")
    @JsonIgnoreProperties({"steps"})
    private Solution solution;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Solution getSolution() {
        return solution;
    }

    public void setSolution(Solution solution) {
        this.solution = solution;
    }
}
