package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

/**
 * Represents a user's vote (upvote or downvote) on a solution.
 */
@Entity
@Table(name = "solution_vote")
public class SolutionVote {

    /**
     * Unique identifier of the vote.
     * Generated by the system.
     * Example: 1001
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Indicates if the vote is an upvote (true) or a downvote (false).
     * Example: true
     */
    @Column(name = "is_up_vote")
    private Boolean isUpVote;

    /**
     * The solution this vote is associated with.
     */
    @ManyToOne
    @JoinColumn(name = "solution_id")
    @JsonIgnoreProperties({"votes", "user"})
    private Solution solution;

    /**
     * The user who cast this vote.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({
            "solutionVotes", "solutions", "questionPool", "createdQuestions",
            "exams", "ownedTopicContents", "approvedTopicContents", "teacherOfTopicContents"
    })
    private User user;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getUpVote() {
        return isUpVote;
    }

    public void setUpVote(Boolean upVote) {
        isUpVote = upVote;
    }

    public Solution getSolution() {
        return solution;
    }

    public void setSolution(Solution solution) {
        this.solution = solution;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
