package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Entity
@Table(name = "solution_step")
@Schema(description = "Represents a single step in a solution to a question.")
public class SolutionStep {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier of the solution step, generated by the system.",
            example = "501",
            readOnly = true
    )
    private Long id;

    @Schema(
            description = "Title or short summary of this step.",
            example = "Step 1: Identify variables"
    )
    private String title;

    @Schema(
            description = "Detailed explanation or content of this step.",
            example = "Define the variables x and y based on the problem statement."
    )
    private String text;

    @ManyToOne
    @JoinColumn(name = "solution_id")
    @JsonIgnoreProperties({"steps"})
    private Solution solution;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Solution getSolution() {
        return solution;
    }

    public void setSolution(Solution solution) {
        this.solution = solution;
    }
}
