package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDate;

/**
 * Tracks the login streak of a user, including the last login date and current streak count.
 */
@Entity
@Table(name = "streak_tracking")
public class StreakTracking {

    /**
     * Unique identifier for the streak tracking record, generated by the system.
     * Example: 10
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Date when the user last logged in.
     * Example: 2025-07-09
     */
    @Column(name = "last_logged_in")
    private LocalDate lastLoggedInAt;

    /**
     * Current number of consecutive days the user has logged in.
     * Example: 5
     */
    private Integer streak;

    /**
     * The user associated with this streak tracking record.
     */
    @OneToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"streakTracking"})
    private User user;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDate getLastLoggedInAt() {
        return lastLoggedInAt;
    }

    public void setLastLoggedInAt(LocalDate lastLoggedInAt) {
        this.lastLoggedInAt = lastLoggedInAt;
    }

    public Integer getStreak() {
        return streak;
    }

    public void setStreak(Integer streak) {
        this.streak = streak;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
