package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.LocalDate;

@Entity
@Table(name = "streak_tracking")
@Schema(description = "Tracks the login streak of a user, including the last login date and current streak count.")
public class StreakTracking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier for the streak tracking record, generated by the system.",
            example = "10",
            readOnly = true
    )
    private Long id;

    @Column(name = "last_logged_in")
    @Schema(
            description = "Date when the user last logged in.",
            example = "2025-07-09"
    )
    private LocalDate lastLoggedInAt;

    @Schema(
            description = "Current number of consecutive days the user has logged in.",
            example = "5"
    )
    private Integer streak;

    @OneToOne
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"streakTracking"})
    private User user;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDate getLastLoggedInAt() {
        return lastLoggedInAt;
    }

    public void setLastLoggedInAt(LocalDate lastLoggedInAt) {
        this.lastLoggedInAt = lastLoggedInAt;
    }

    public Integer getStreak() {
        return streak;
    }

    public void setStreak(Integer streak) {
        this.streak = streak;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
