package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

@Entity
@Schema(description = "Represents a subject or field of study, containing related topic pools.")
public class Subject {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(
            description = "Unique identifier for the subject, generated by the system.",
            example = "3",
            readOnly = true
    )
    private Long id;

    @Schema(
            description = "The name of the subject.",
            example = "Mathematics"
    )
    private String name;

    @Schema(
            description = "A description of the subject.",
            example = "Covers topics like algebra, calculus, and geometry."
    )
    private String description;

    @ManyToOne
    @JoinColumn(name = "img_id")
    @Schema(
            description = "Optional image representing the subject.",
            implementation = MediaFile.class
    )
    private MediaFile img;

    @OneToMany(mappedBy = "subject")
    @JsonIgnoreProperties({"subject"})
    private List<TopicPool> topicPools;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public MediaFile getImg() {
        return img;
    }

    public void setImg(MediaFile img) {
        this.img = img;
    }

    public List<TopicPool> getTopicPools() {
        return topicPools;
    }

    public void setTopicPools(List<TopicPool> topicPools) {
        this.topicPools = topicPools;
    }
}
