package at.learnhub.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

/**
 * Represents a subject or field of study, such as Mathematics or Biology.
 * Contains descriptive information and related topic pools.
 */
@Entity
public class Subject {

    /**
     * Unique identifier for the subject, generated by the system.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the subject.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * A description of the subject, e.g., "Covers topics like algebra, calculus, and geometry."
     */
    private String description;

    /**
     * Optional image representing the subject.
     */
    @ManyToOne
    @JoinColumn(name = "img_id")
    private MediaFile img;

    /**
     * The list of topic pools related to this subject.
     */
    @OneToMany(mappedBy = "subject", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnoreProperties({"subject"})
    private List<TopicPool> topicPools;

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public MediaFile getImg() {
        return img;
    }

    public void setImg(MediaFile img) {
        this.img = img;
    }

    public List<TopicPool> getTopicPools() {
        return topicPools;
    }

    public void setTopicPools(List<TopicPool> topicPools) {
        this.topicPools = topicPools;
    }
}
