quarkus.package.type=uber-jar

# Keycloak Configuration
keycloak.realm.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkfp9Zie1tC3lWSb+21Fy2gsZAzs5vmsuXOmVNFBcvm8ka0qd6CWi+D/qE0hFx7SI1MpDwInU7Lddu67Nm63Vzh8UzZtDurrllXcl7sxgRHvPCj/8RFIXCpqLJMQsfCv5vyy1J9K+08ugZmPNqabrONwawVw+2tOliXu7qz/zxvALdUGB9FUUleYR/nrvz8V5HQMzwKFl7LMCySFegdhHTMvi1pjnshcx+SrK/F1EzTjPV7R/Qf2FDZnMkmm4jGMhQFn9CZZ/gQtAVA2OsnuHmcFef8QNU6hBl/mu+hoT9QHZUV5b8afbaS6RMSp3ytQoY+ppXfbjupSWEknKEmRexwIDAQAB

#quarkus.oidc.auth-server-url=https://auth.htl-leonding.ac.at/realms/2526_5bhitm
#quarkus.oidc.client-id=frontend
#quarkus.oidc.application-type=service
#quarkus.oidc.tls.verification=none

# ALLES absichern
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated

# enable cors for angular
# ---- DEV (lokal) ----
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:4200
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
%dev.quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
%dev.quarkus.http.cors.exposed-headers=location,link
quarkus.http.cors.headers=Content-Type,Authorization
%dev.quarkus.http.cors.access-control-allow-credentials=true

# ---- PROD (Server) ----
%prod.quarkus.http.cors=true
%prod.quarkus.http.cors.origins=https://vm91.htl-leonding.ac.at
%prod.quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
%prod.quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
%prod.quarkus.http.cors.exposed-headers=location,link
%prod.quarkus.http.cors.access-control-allow-credentials=true

# Dev (default) - H2 in memory for local development
quarkus.datasource.devservices.enabled=true
quarkus.hibernate-orm.enabled=true
quarkus.package.jar.type=uber-jar
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=drop-and-create


# Prod: Dockerized MySQL
%prod.quarkus.datasource.db-kind=mysql
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/learnhub-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
%prod.quarkus.hibernate-orm.database.generation=update


# Enable OpenAPI and Swagger UI in prod
%prod.quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.path=/q/swagger-ui
%prod.quarkus.smallrye-openapi.path=/q/openapi
%prod.quarkus.smallrye-openapi.enable=true
%prod.quarkus.smallrye-openapi.yaml-code-point-limit=10000000
%prod.quarkus.http.limits.max-body-size=100M

app.upload.dir=/app/uploads
app.public.base=http://vm91.htl-leonding.ac.at/uploads/
quarkus.http.limits.max-body-size=25M

%dev.quarkus.http.auth.permission.public.paths=/*
%dev.quarkus.http.auth.permission.public.policy=permit

%prod.quarkus.http.auth.permission.uploads.paths=/uploads/*
%prod.quarkus.http.auth.permission.uploads.policy=permit

%prod.quarkus.http.auth.permission.public.paths=/api/users/register,/api/users/me,/q/*
%prod.quarkus.http.auth.permission.public.policy=permit

%prod.quarkus.http.auth.permission.api.paths=/api/*
%prod.quarkus.http.auth.permission.api.policy=authenticated



# Define a security scheme named 'BearerAuth'
quarkus.smallrye-openapi.security-schemes.BearerAuth.type=http
# Specify the scheme itself as 'bearer' (which makes it a Bearer Token)
quarkus.smallrye-openapi.security-schemes.BearerAuth.scheme=bearer
# (Optional) Specify the format of the token
quarkus.smallrye-openapi.security-schemes.BearerAuth.bearer-format=JWT
