name: Build and Push on backend changes

on:
  push:
    paths:
      - 'backend/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL container
      run: docker compose up -d mysql
      working-directory: ./backend

    - name: Wait for MySQL to initialize
      run: sleep 15

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Maven project
      run: ./mvnw clean package
      working-directory: ./backend

    - name: Build and start all containers
      run: docker compose up --build -d
      working-directory: ./backend

    - name: Stop and remove all containers
      run: docker compose down
      working-directory: ./backend

    - name: Get last commit message
      id: get_message
      run: echo "::set-output name=msg::$(git log -1 --pretty=%B | head -n1)"

    - name: Commit changes if any
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add backend
          if ! git diff --cached --quiet; then
            git commit -m "${{ steps.get_message.outputs.msg }} [ci skip]"
            git push
          else
            echo "No changes to commit"
          fi
